# Generated by Django 4.2.27 on 2026-01-03 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalapp",
            name="backend_connection",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional backend connection for data access",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="internal_apps",
                to="relay_app.backendconnection",
            ),
        ),
    ]
