# Generated by Django 4.2.27 on 2026-01-03 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0002_make_backend_connection_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backendconnection",
            name="adapter_type",
            field=models.CharField(
                choices=[
                    ("supabase", "Supabase"),
                    ("postgresql", "PostgreSQL"),
                    ("mysql", "MySQL"),
                ],
                default="supabase",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Chat", max_length=255)),
                (
                    "model_id",
                    models.CharField(
                        default="anthropic/claude-3.5-sonnet",
                        help_text="AI model used for this session",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="relay_app.internalapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("streaming", "Streaming"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="complete",
                        max_length=20,
                    ),
                ),
                ("model_id", models.CharField(blank=True, max_length=100, null=True)),
                ("token_count_input", models.IntegerField(blank=True, null=True)),
                ("token_count_output", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "generated_spec_json",
                    models.JSONField(
                        blank=True,
                        help_text="Generated AppSpec JSON if this was a spec generation",
                        null=True,
                    ),
                ),
                (
                    "generated_files",
                    models.JSONField(
                        blank=True,
                        help_text="Generated code files {path: content}",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="relay_app.chatsession",
                    ),
                ),
                (
                    "version_created",
                    models.ForeignKey(
                        blank=True,
                        help_text="Version created from this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_messages",
                        to="relay_app.appversion",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_model",
                    models.CharField(
                        default="anthropic/claude-3.5-sonnet", max_length=100
                    ),
                ),
                (
                    "fallback_model",
                    models.CharField(
                        default="openai/gpt-4o-mini",
                        help_text="Model to use if primary fails",
                        max_length=100,
                    ),
                ),
                ("temperature", models.FloatField(default=0.3)),
                ("max_tokens", models.IntegerField(default=8192)),
                (
                    "system_prompt_override",
                    models.TextField(
                        blank=True,
                        help_text="Custom system prompt to prepend",
                        null=True,
                    ),
                ),
                (
                    "coding_guidelines",
                    models.TextField(
                        blank=True,
                        help_text="Custom coding guidelines for generation",
                        null=True,
                    ),
                ),
                ("enable_streaming", models.BooleanField(default=True)),
                (
                    "enable_auto_apply",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-apply generated code without confirmation",
                    ),
                ),
                (
                    "enable_thinking_display",
                    models.BooleanField(
                        default=True, help_text="Show AI thinking process"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_configs",
                        to="relay_app.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CodeGenerationJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("streaming", "Streaming"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("progress_message", models.CharField(blank=True, max_length=255)),
                ("accumulated_content", models.TextField(blank=True)),
                ("chunk_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "chat_message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_job",
                        to="relay_app.chatmessage",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="relay_app.internalapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["internal_app", "status"],
                        name="relay_app_c_interna_e4e389_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="relay_app_c_status_d8d056_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="relay_app_c_interna_bf285b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="relay_app_c_session_6a54aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentconfiguration",
            unique_together={("organization", "name")},
        ),
    ]
