# Generated by Django 4.2.27 on 2026-01-03 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0003_chat_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_id", models.CharField(max_length=100)),
                ("request_type", models.CharField(max_length=50)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("cost_input_cents", models.IntegerField(default=0)),
                ("cost_output_cents", models.IntegerField(default=0)),
                ("total_cost_cents", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="relay_app.chatmessage",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to="relay_app.internalapp",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to="relay_app.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="relay_app_a_organiz_f973da_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="relay_app_a_user_id_337db9_idx",
                    ),
                    models.Index(
                        fields=["model_id", "-created_at"],
                        name="relay_app_a_model_i_02a1e7_idx",
                    ),
                ],
            },
        ),
    ]
