# Generated by Django 4.2.27 on 2026-01-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0004_ai_usage_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Organization logo image",
                null=True,
                upload_to="org_logos/",
            ),
        ),
    ]
