# Generated by Django 4.2.27 on 2026-01-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0005_add_organization_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="appversion",
            name="generation_current_step",
            field=models.IntegerField(
                default=0, help_text="Current step index in generation plan"
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="generation_error",
            field=models.TextField(
                blank=True, help_text="Error message if generation failed", null=True
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="generation_plan_json",
            field=models.JSONField(
                blank=True, help_text="Current plan for agentic generation", null=True
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="generation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("complete", "Complete"),
                    ("error", "Error"),
                ],
                default="complete",
                help_text="Status of agentic code generation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agentconfiguration",
            name="default_model",
            field=models.CharField(default="anthropic/claude-sonnet-4", max_length=100),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="model_id",
            field=models.CharField(
                default="anthropic/claude-sonnet-4",
                help_text="AI model used for this session",
                max_length=100,
            ),
        ),
    ]
