# Generated by Django 5.2.9 on 2026-01-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0006_add_generation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionexecutionlog",
            name="executed_by",
        ),
        migrations.RemoveField(
            model_name="actionexecutionlog",
            name="input_json",
        ),
        migrations.RemoveField(
            model_name="actionexecutionlog",
            name="output_json",
        ),
        migrations.AddField(
            model_name="actionexecutionlog",
            name="args_json",
            field=models.JSONField(default=dict, help_text="Input arguments payload"),
        ),
        migrations.AddField(
            model_name="actionexecutionlog",
            name="backend_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to="relay_app.backendconnection",
            ),
        ),
        migrations.AddField(
            model_name="actionexecutionlog",
            name="internal_app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_logs",
                to="relay_app.internalapp",
            ),
        ),
        migrations.AddField(
            model_name="actionexecutionlog",
            name="resource_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="actionexecutionlog",
            name="result_json",
            field=models.JSONField(
                blank=True, help_text="Adapter execution result", null=True
            ),
        ),
        migrations.AddField(
            model_name="actionexecutionlog",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("error", "Error")],
                default="success",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="actionexecutionlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="intent_message",
            field=models.TextField(
                blank=True,
                help_text="User intent that generated this version (AI edits)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent version used as the base for this version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_versions",
                to="relay_app.appversion",
            ),
        ),
        migrations.AddField(
            model_name="versionfile",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Deterministic hash of the file content for integrity checks",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="actionexecutionlog",
            name="app_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_logs",
                to="relay_app.appversion",
            ),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="source",
            field=models.CharField(
                choices=[
                    ("ai_edit", "AI Edit"),
                    ("code_edit", "Code Edit"),
                    ("rollback", "Rollback"),
                    ("publish", "Publish"),
                    ("ai", "AI (legacy)"),
                    ("code", "Code (legacy)"),
                ],
                default="ai_edit",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="actionexecutionlog",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="relay_app_a_interna_492757_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actionexecutionlog",
            index=models.Index(
                fields=["backend_connection", "-created_at"],
                name="relay_app_a_backend_b27e7b_idx",
            ),
        ),
    ]
