# Generated by Django 5.2.9 on 2026-01-05 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0007_remove_actionexecutionlog_executed_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppDataTable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "schema_json",
                    models.JSONField(
                        default=dict,
                        help_text="Table schema: columns, types, constraints",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_tables",
                        to="relay_app.internalapp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppDataRow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Row data matching table schema"
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(
                        help_text="Sequential index within table"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="relay_app.appdatatable",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index"],
            },
        ),
        migrations.CreateModel(
            name="AppDataQuery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "query_spec",
                    models.JSONField(
                        help_text="Query specification: filters, sort, pagination"
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_queries",
                        to="relay_app.internalapp",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_queries",
                        to="relay_app.appdatatable",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="appdatatable",
            index=models.Index(
                fields=["internal_app", "slug"], name="relay_app_a_interna_947b37_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appdatatable",
            unique_together={("internal_app", "slug")},
        ),
        migrations.AddIndex(
            model_name="appdatarow",
            index=models.Index(
                fields=["table", "row_index"], name="relay_app_a_table_i_bdbc82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appdatarow",
            index=models.Index(
                fields=["table", "created_at"], name="relay_app_a_table_i_1f494a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appdataquery",
            unique_together={("internal_app", "name")},
        ),
    ]
