# Generated by Django 5.2.9 on 2026-01-05 02:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0008_app_data_store"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppDataTableSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schema_json",
                    models.JSONField(help_text="Table schema frozen at this version"),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Table name at this version", max_length=255
                    ),
                ),
                (
                    "table_slug",
                    models.SlugField(
                        help_text="Table slug at this version", max_length=255
                    ),
                ),
                (
                    "table_description",
                    models.TextField(
                        blank=True, help_text="Table description at this version"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        help_text="Operation that created this snapshot",
                        max_length=20,
                    ),
                ),
                (
                    "previous_schema_json",
                    models.JSONField(
                        blank=True,
                        help_text="Previous schema (for update operations)",
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        help_text="The app version this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_snapshots",
                        to="relay_app.appversion",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="The table this snapshot is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="relay_app.appdatatable",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["app_version", "table"],
                        name="relay_app_a_app_ver_197c03_idx",
                    ),
                    models.Index(
                        fields=["table", "created_at"],
                        name="relay_app_a_table_i_5afb71_idx",
                    ),
                ],
                "unique_together": {("app_version", "table")},
            },
        ),
    ]
