# Generated by Django 4.2.27 on 2026-01-05 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0009_app_data_table_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionStateSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tables_json",
                    models.JSONField(
                        default=list,
                        help_text="Array of {id, slug, name, description, schema, row_count} for all tables",
                    ),
                ),
                (
                    "resources_json",
                    models.JSONField(
                        default=list,
                        help_text="Array of resource registry entries exposed to this app",
                    ),
                ),
                (
                    "total_tables",
                    models.IntegerField(
                        default=0, help_text="Number of data tables at this version"
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(
                        default=0,
                        help_text="Total row count across all tables at this version",
                    ),
                ),
                (
                    "file_count",
                    models.IntegerField(
                        default=0, help_text="Number of code files at this version"
                    ),
                ),
                (
                    "app_version",
                    models.OneToOneField(
                        help_text="The version this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_snapshot",
                        to="relay_app.appversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["app_version"], name="relay_app_v_app_ver_7ba957_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VersionAuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("rollback", "Rollback"),
                            ("publish", "Publish"),
                            ("schema_revert", "Schema Revert"),
                            ("preview", "Preview"),
                        ],
                        help_text="The type of operation performed",
                        max_length=20,
                    ),
                ),
                (
                    "details_json",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed operation context and parameters",
                    ),
                ),
                (
                    "schema_changes_json",
                    models.JSONField(
                        blank=True,
                        help_text="Summary of schema changes for rollback operations",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user performing the operation",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string of the client",
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the operation completed successfully",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if operation failed",
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        help_text="The version affected by this operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="relay_app.appversion",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        help_text="The app this audit log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_audit_logs",
                        to="relay_app.internalapp",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="For rollback operations, the version being rolled back from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_audit_logs",
                        to="relay_app.appversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["internal_app", "-created_at"],
                        name="relay_app_v_interna_44e359_idx",
                    ),
                    models.Index(
                        fields=["app_version", "-created_at"],
                        name="relay_app_v_app_ver_3c221b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="relay_app_v_user_id_c4f221_idx",
                    ),
                    models.Index(
                        fields=["operation", "-created_at"],
                        name="relay_app_v_operati_486a92_idx",
                    ),
                ],
            },
        ),
    ]
