# Generated by Django 5.2.9 on 2026-01-05 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0011_add_is_active_to_appversion"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appversion",
            name="relay_app_a_interna_active_idx",
        ),
        migrations.AddField(
            model_name="internalapp",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The currently active published version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_for_app",
                to="relay_app.appversion",
            ),
        ),
        migrations.AddField(
            model_name="internalapp",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier for the app (auto-generated from name if not set)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="internalapp",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="internalapp",
            index=models.Index(
                fields=["organization", "slug"], name="relay_app_i_organiz_13a519_idx"
            ),
        ),
    ]
