# Generated by Django 5.2.9 on 2026-01-05 22:57

from django.db import migrations
from django.utils.text import slugify


def backfill_slugs_and_published_versions(apps, schema_editor):
    """
    Backfill slugs for existing apps and set published_version for apps
    that have publish-type versions.
    """
    InternalApp = apps.get_model('relay_app', 'InternalApp')
    AppVersion = apps.get_model('relay_app', 'AppVersion')
    
    for app in InternalApp.objects.all():
        # Generate slug if not set
        if not app.slug:
            base_slug = slugify(app.name)
            if not base_slug:
                base_slug = 'app'
            
            # Ensure uniqueness within organization
            slug = base_slug
            counter = 1
            while InternalApp.objects.filter(
                organization=app.organization,
                slug=slug
            ).exclude(pk=app.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            app.slug = slug
        
        # Find latest publish version and set as published_version
        if app.status == 'published' and not app.published_version:
            latest_publish_version = AppVersion.objects.filter(
                internal_app=app,
                source='publish'
            ).order_by('-version_number').first()
            
            if latest_publish_version:
                app.published_version = latest_publish_version
        
        app.save()


def reverse_backfill(apps, schema_editor):
    """
    Reverse the backfill - clear slugs and published_version.
    """
    InternalApp = apps.get_model('relay_app', 'InternalApp')
    InternalApp.objects.all().update(slug=None, published_version=None)


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0012_add_slug_and_published_version_to_internalapp"),
    ]

    operations = [
        migrations.RunPython(
            backfill_slugs_and_published_versions,
            reverse_backfill
        ),
    ]
