# Generated by Django 5.2.9 on 2026-01-05 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0013_backfill_app_slugs_and_published_versions"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeIntegrationProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "merge_tool_pack_id",
                    models.CharField(
                        help_text="Tool Pack ID from Merge Agent Handler dashboard",
                        max_length=255,
                    ),
                ),
                (
                    "merge_access_key_encrypted",
                    models.TextField(
                        help_text="Encrypted production access key for Merge API"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(default="Integrations", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_providers",
                        to="relay_app.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization",)},
            },
        ),
        migrations.CreateModel(
            name="ConnectorCache",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connector_id",
                    models.CharField(
                        help_text='Connector ID from Merge (e.g., "jira", "linear", "slack")',
                        max_length=255,
                    ),
                ),
                (
                    "connector_name",
                    models.CharField(
                        help_text='Display name (e.g., "Jira", "Linear", "Slack")',
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text='Category (e.g., "project_management", "communication")',
                        max_length=100,
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True, help_text="URL to connector icon/logo", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the connector"
                    ),
                ),
                (
                    "tools_json",
                    models.JSONField(
                        default=list,
                        help_text="List of available tools: [{id, name, description, parameters}]",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this connector is enabled for the organization",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this connector was synced from Merge",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="relay_app.mergeintegrationprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["connector_name"],
                "unique_together": {("provider", "connector_id")},
            },
        ),
        migrations.CreateModel(
            name="MergeIntegrationUser",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "merge_registered_user_id",
                    models.CharField(
                        help_text="Registered user ID from Merge Agent Handler",
                        max_length=255,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_users",
                        to="relay_app.mergeintegrationprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "provider")},
            },
        ),
        migrations.CreateModel(
            name="ConnectorExecutionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connector_slug",
                    models.CharField(
                        help_text='Connector ID slug (e.g., "jira")', max_length=255
                    ),
                ),
                ("tool_id", models.CharField(max_length=255)),
                (
                    "params_json",
                    models.JSONField(default=dict, help_text="Input parameters"),
                ),
                (
                    "result_json",
                    models.JSONField(
                        blank=True, help_text="Execution result", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="relay_app.connectorcache",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_logs",
                        to="relay_app.internalapp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connector_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["internal_app", "-created_at"],
                        name="relay_app_c_interna_98f8f4_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="relay_app_c_user_id_3f2a77_idx",
                    ),
                    models.Index(
                        fields=["connector_slug", "-created_at"],
                        name="relay_app_c_connect_cc8fc4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserConnectorLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_connected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has successfully connected this connector",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user connected this connector",
                        null=True,
                    ),
                ),
                (
                    "connection_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the connection",
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_links",
                        to="relay_app.connectorcache",
                    ),
                ),
                (
                    "integration_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_links",
                        to="relay_app.mergeintegrationuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("integration_user", "connector")},
            },
        ),
    ]
