# Generated by Django 5.2.9 on 2026-01-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0015_org_level_connectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectorcache",
            name="categories_json",
            field=models.JSONField(
                default=list,
                help_text='List of category tags (e.g., ["Project Management", "Ticketing"])',
            ),
        ),
        migrations.AddField(
            model_name="connectorcache",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="URL to connector logo image", null=True
            ),
        ),
        migrations.AddField(
            model_name="connectorcache",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text='Source website URL (e.g., "https://linear.app")',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connectorcache",
            name="icon_url",
            field=models.URLField(
                blank=True, help_text="Deprecated: Use logo_url instead", null=True
            ),
        ),
    ]
