# Generated by Django 5.2.9 on 2026-01-06 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0016_add_connector_metadata_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorganization",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                default="editor",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrganizationInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address this invitation is for",
                        max_length=254,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="editor",
                        help_text="Role the user will have when they accept",
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA256 hash of the invitation token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this invitation expires"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted",
                        null=True,
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this invitation has been accepted",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="relay_app.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "email"],
                        name="relay_app_o_organiz_1ed47f_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="relay_app_o_expires_0bb882_idx"
                    ),
                    models.Index(
                        fields=["token_hash"], name="relay_app_o_token_h_32b3c0_idx"
                    ),
                ],
            },
        ),
    ]
