# Generated by Django 5.2.9 on 2026-01-06 16:38

from django.db import migrations


def migrate_member_to_editor(apps, schema_editor):
    """
    Convert existing 'member' roles to 'editor' to preserve current behavior.
    The new permission system uses: admin, editor, viewer
    """
    UserOrganization = apps.get_model('relay_app', 'UserOrganization')
    updated = UserOrganization.objects.filter(role='member').update(role='editor')
    if updated:
        print(f"Migrated {updated} 'member' roles to 'editor'")


def reverse_editor_to_member(apps, schema_editor):
    """Reverse migration: convert 'editor' back to 'member'."""
    UserOrganization = apps.get_model('relay_app', 'UserOrganization')
    UserOrganization.objects.filter(role='editor').update(role='member')


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0017_add_permission_roles_and_invites"),
    ]

    operations = [
        migrations.RunPython(migrate_member_to_editor, reverse_editor_to_member),
    ]
