# Generated by Django 5.2.9 on 2026-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0019_add_app_favorite_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="appversion",
            name="fix_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of auto-fix attempts made"
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="validation_errors_json",
            field=models.JSONField(
                blank=True,
                help_text="JSON list of validation errors if failed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                help_text="TypeScript compilation validation status",
                max_length=20,
            ),
        ),
    ]
