# Generated by Django 5.2.9 on 2026-01-08 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relay_app", "0020_add_validation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="codegenerationjob",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="codegenerationjob",
            name="events_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="codegenerationjob",
            name="model_id",
            field=models.CharField(default="anthropic/claude-sonnet-4", max_length=100),
        ),
        migrations.AddField(
            model_name="codegenerationjob",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_jobs",
                to="relay_app.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="codegenerationjob",
            name="user_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="codegenerationjob",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_job",
                to="relay_app.appversion",
            ),
        ),
        migrations.AlterField(
            model_name="codegenerationjob",
            name="chat_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_job",
                to="relay_app.chatmessage",
            ),
        ),
    ]
