# Generated by Django 6.0.1 on 2026-01-15 22:55

import chat.types
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="New Chat", max_length=255)),
                (
                    "model_id",
                    models.CharField(
                        default="anthropic/claude-sonnet-4.5",
                        help_text="AI model used for this session",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="apps.internalapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "USER"),
                            ("assistant", "ASSISTANT"),
                            ("system", "SYSTEM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("streaming", "STREAMING"),
                            ("complete", "COMPLETE"),
                            ("error", "ERROR"),
                        ],
                        default=chat.types.ChatMessageStatus["COMPLETE"],
                        max_length=20,
                    ),
                ),
                ("model_id", models.CharField(blank=True, max_length=100, null=True)),
                ("token_count_input", models.IntegerField(blank=True, null=True)),
                ("token_count_output", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "generated_spec_json",
                    models.JSONField(
                        blank=True,
                        help_text="Generated AppSpec JSON if this was a spec generation",
                        null=True,
                    ),
                ),
                (
                    "generated_files",
                    models.JSONField(
                        blank=True,
                        help_text="Generated code files {path: content}",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "version_created",
                    models.ForeignKey(
                        blank=True,
                        help_text="Version created from this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_messages",
                        to="apps.appversion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_message", models.TextField(blank=True)),
                (
                    "model_id",
                    models.CharField(
                        default="anthropic/claude-sonnet-4.5", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "QUEUED"),
                            ("processing", "PROCESSING"),
                            ("streaming", "STREAMING"),
                            ("complete", "COMPLETE"),
                            ("failed", "FAILED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        default=chat.types.CodeGenerationJobStatus["QUEUED"],
                        max_length=20,
                    ),
                ),
                ("chunk_count", models.IntegerField(default=0)),
                ("events_json", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "chat_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_job",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="apps.internalapp",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="chat.chatsession",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_job",
                        to="apps.appversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="chat_chatse_interna_6d6295_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chat_chatme_session_70d41b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codegenerationjob",
            index=models.Index(
                fields=["internal_app", "status"], name="chat_codege_interna_b49b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codegenerationjob",
            index=models.Index(
                fields=["status", "-created_at"], name="chat_codege_status_ec3439_idx"
            ),
        ),
    ]
