# Generated by Django 4.2.27 on 2026-01-16 19:39

import chat.types
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileVerificationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_path",
                    models.CharField(help_text="Path of the verified file", max_length=500),
                ),
                (
                    "file_type",
                    models.CharField(
                        help_text='File extension (e.g., ".ts", ".tsx")', max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("passed", "PASSED"),
                            ("failed", "FAILED"),
                            ("skipped", "SKIPPED"),
                            ("error", "ERROR"),
                        ],
                        default=chat.types.VerificationStatus["PENDING"],
                        help_text="Final verification status",
                        max_length=20,
                    ),
                ),
                (
                    "verifier_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the verifier used (e.g., 'typescript')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "final_content",
                    models.TextField(
                        blank=True, help_text="The file content after all retries", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Final error message if verification failed",
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When verification started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When verification completed", null=True
                    ),
                ),
                (
                    "code_generation_job",
                    models.ForeignKey(
                        blank=True,
                        help_text="The code generation job that triggered this verification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_records",
                        to="chat.codegenerationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationAttemptRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt_number",
                    models.PositiveIntegerField(help_text="Attempt number (1-based)"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The code content that was verified in this attempt"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("passed", "PASSED"),
                            ("failed", "FAILED"),
                            ("skipped", "SKIPPED"),
                            ("error", "ERROR"),
                        ],
                        help_text="Status of this specific attempt",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if this attempt failed", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, help_text="When this attempt occurred", null=True
                    ),
                ),
                (
                    "verification_record",
                    models.ForeignKey(
                        help_text="The verification record this attempt belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="chat.fileverificationrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt_number"],
                "indexes": [
                    models.Index(
                        fields=["verification_record", "attempt_number"],
                        name="chat_verifi_verific_3eee33_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="fileverificationrecord",
            index=models.Index(
                fields=["code_generation_job", "-created_at"], name="chat_fileve_code_ge_55ebf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileverificationrecord",
            index=models.Index(
                fields=["status", "-created_at"], name="chat_fileve_status_6a4242_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileverificationrecord",
            index=models.Index(
                fields=["file_type", "-created_at"], name="chat_fileve_file_ty_c8741c_idx"
            ),
        ),
    ]
