# Generated by Django 4.2.27 on 2026-01-16 07:14

import chat.types
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codegenerationjob",
            name="questioning_session",
            field=models.ForeignKey(
                blank=True,
                help_text="QuestioningSession that gathered requirements for this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_jobs",
                to="chat.questioningsession",
            ),
        ),
        migrations.AlterField(
            model_name="codegenerationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("questioning", "QUESTIONING"),
                    ("queued", "QUEUED"),
                    ("processing", "PROCESSING"),
                    ("streaming", "STREAMING"),
                    ("complete", "COMPLETE"),
                    ("failed", "FAILED"),
                    ("cancelled", "CANCELLED"),
                ],
                default=chat.types.CodeGenerationJobStatus["QUEUED"],
                max_length=20,
            ),
        ),
    ]
