# Generated by Django 4.2.27 on 2026-01-16 02:57

import chat.types
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_questioningjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="context",
            field=models.CharField(
                choices=[("requirements", "REQUIREMENTS"), ("build", "BUILD")],
                default=chat.types.ChatMessageContext["BUILD"],
                help_text="Which phase/tab this message belongs to (requirements or build)",
                max_length=20,
            ),
        ),
    ]
