# Generated by Django 4.2.27 on 2026-01-15 03:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import vector_app.action_classification.types
import vector_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True,
                        help_text="Google user ID for OAuth",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Profile image URL from OAuth provider (legacy)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "profile_image_storage_key",
                    models.CharField(
                        blank=True,
                        help_text="Storage key for uploaded profile image (supports cloud and local storage)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AppDataTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "schema_json",
                    models.JSONField(
                        default=dict,
                        help_text="Table schema: columns, types, constraints",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                (
                    "spec_json",
                    models.JSONField(help_text="AppSpec JSON for this version"),
                ),
                (
                    "intent_message",
                    models.TextField(
                        blank=True,
                        help_text="User intent that generated this version (AI edits)",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai_edit", "AI_EDIT"),
                            ("code_edit", "CODE_EDIT"),
                            ("rollback", "ROLLBACK"),
                            ("publish", "PUBLISH"),
                            ("ai", "AI"),
                            ("code", "CODE"),
                        ],
                        default=vector_app.models.AppVersionSource["AI_EDIT"],
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this version is active and should be returned by API. Only set True when generation completes successfully.",
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("generating", "GENERATING"),
                            ("complete", "COMPLETE"),
                            ("error", "ERROR"),
                        ],
                        default=vector_app.models.AppVersionGenerationStatus[
                            "COMPLETE"
                        ],
                        help_text="Status of agentic code generation",
                        max_length=20,
                    ),
                ),
                (
                    "generation_plan_json",
                    models.JSONField(
                        blank=True,
                        help_text="Current plan for agentic generation",
                        null=True,
                    ),
                ),
                (
                    "generation_current_step",
                    models.IntegerField(
                        default=0, help_text="Current step index in generation plan"
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("passed", "PASSED"),
                            ("failed", "FAILED"),
                            ("skipped", "SKIPPED"),
                        ],
                        default=vector_app.models.AppVersionValidationStatus["PENDING"],
                        help_text="TypeScript compilation validation status",
                        max_length=20,
                    ),
                ),
                (
                    "validation_errors_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of validation errors if failed",
                        null=True,
                    ),
                ),
                (
                    "fix_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of auto-fix attempts made"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "USER"),
                            ("assistant", "ASSISTANT"),
                            ("system", "SYSTEM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("streaming", "STREAMING"),
                            ("complete", "COMPLETE"),
                            ("error", "ERROR"),
                        ],
                        default=vector_app.models.ChatMessageStatus["COMPLETE"],
                        max_length=20,
                    ),
                ),
                ("model_id", models.CharField(blank=True, max_length=100, null=True)),
                ("token_count_input", models.IntegerField(blank=True, null=True)),
                ("token_count_output", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "generated_spec_json",
                    models.JSONField(
                        blank=True,
                        help_text="Generated AppSpec JSON if this was a spec generation",
                        null=True,
                    ),
                ),
                (
                    "generated_files",
                    models.JSONField(
                        blank=True,
                        help_text="Generated code files {path: content}",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="New Chat", max_length=255)),
                (
                    "model_id",
                    models.CharField(
                        default="anthropic/claude-sonnet-4.5",
                        help_text="AI model used for this session",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectorCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connector_id",
                    models.CharField(
                        help_text='Connector ID from Merge (e.g., "jira", "linear", "slack")',
                        max_length=255,
                    ),
                ),
                (
                    "connector_name",
                    models.CharField(
                        help_text='Display name (e.g., "Jira", "Linear", "Slack")',
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text='Category (e.g., "project_management", "communication")',
                        max_length=100,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="URL to connector logo image", null=True
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text='Source website URL (e.g., "https://linear.app")',
                        null=True,
                    ),
                ),
                (
                    "categories_json",
                    models.JSONField(
                        default=list,
                        help_text='List of category tags (e.g., ["Project Management", "Ticketing"])',
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the connector"
                    ),
                ),
                (
                    "tools_json",
                    models.JSONField(
                        default=list,
                        help_text="List of available tools: [{id, name, description, parameters}]",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this connector is enabled for the organization",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this connector was synced from Merge",
                    ),
                ),
            ],
            options={
                "ordering": ["connector_name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo image (legacy - use logo_storage_key for new uploads)",
                        null=True,
                        upload_to="org_logos/",
                    ),
                ),
                (
                    "logo_storage_key",
                    models.CharField(
                        blank=True,
                        help_text="Storage key for logo image (supports cloud and local storage)",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MergeIntegrationProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merge_tool_pack_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DEPRECATED: Tool Pack ID now comes from environment variables",
                        max_length=255,
                    ),
                ),
                (
                    "merge_access_key_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="DEPRECATED: Access key now comes from environment variables",
                    ),
                ),
                (
                    "merge_registered_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Organization registered user ID from Merge (set after first link)",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(default="Integrations", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_providers",
                        to="vector_app.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization",)},
            },
        ),
        migrations.CreateModel(
            name="MagicLinkToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address this magic link is for",
                        max_length=254,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA256 hash of the magic link token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this magic link expires"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been used"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name for new user registration",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name for new user registration",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that requested this magic link",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent that requested this magic link",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="vector_app__email_1626bc_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="vector_app__expires_24a522_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InternalApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier for the app (auto-generated from name if not set)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "DRAFT"), ("published", "PUBLISHED")],
                        default=vector_app.models.InternalAppStatus["DRAFT"],
                        max_length=20,
                    ),
                ),
                ("allow_actions_in_preview", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_apps",
                        to="vector_app.organization",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The currently active published version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_for_app",
                        to="vector_app.appversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConnectorToolAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool_id",
                    models.CharField(
                        help_text='Tool identifier (e.g., "create_issue")',
                        max_length=255,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Display name for the tool", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the tool"
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict, help_text="Full JSON Schema for tool parameters"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("QUERY", "QUERY"),
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                            ("SEND", "SEND"),
                            ("OTHER", "OTHER"),
                        ],
                        default=vector_app.action_classification.types.ActionType[
                            "OTHER"
                        ],
                        help_text="Categorized action type (query, create, update, delete, send, other)",
                        max_length=20,
                    ),
                ),
                (
                    "connector_cache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorized_tools",
                        to="vector_app.connectorcache",
                    ),
                ),
            ],
            options={
                "ordering": ["action_type", "tool_name"],
            },
        ),
        migrations.CreateModel(
            name="ConnectorExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connector_slug",
                    models.CharField(
                        help_text='Connector ID slug (e.g., "jira")', max_length=255
                    ),
                ),
                ("tool_id", models.CharField(max_length=255)),
                (
                    "params_json",
                    models.JSONField(default=dict, help_text="Input parameters"),
                ),
                (
                    "result_json",
                    models.JSONField(
                        blank=True, help_text="Execution result", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "SUCCESS"), ("error", "ERROR")],
                        default=vector_app.models.ConnectorExecutionStatus["SUCCESS"],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="vector_app.connectorcache",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_logs",
                        to="vector_app.internalapp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connector_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="connectorcache",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connectors",
                to="vector_app.mergeintegrationprovider",
            ),
        ),
        migrations.CreateModel(
            name="CodeGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_message", models.TextField(blank=True)),
                (
                    "model_id",
                    models.CharField(
                        default="anthropic/claude-sonnet-4.5", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "QUEUED"),
                            ("processing", "PROCESSING"),
                            ("streaming", "STREAMING"),
                            ("complete", "COMPLETE"),
                            ("failed", "FAILED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        default=vector_app.models.CodeGenerationJobStatus["QUEUED"],
                        max_length=20,
                    ),
                ),
                ("chunk_count", models.IntegerField(default=0)),
                ("events_json", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "chat_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_job",
                        to="vector_app.chatmessage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="vector_app.internalapp",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="vector_app.chatsession",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_job",
                        to="vector_app.appversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="internal_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="vector_app.internalapp",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="vector_app.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="version_created",
            field=models.ForeignKey(
                blank=True,
                help_text="Version created from this message",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_messages",
                to="vector_app.appversion",
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="internal_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="vector_app.internalapp",
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent version used as the base for this version",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_versions",
                to="vector_app.appversion",
            ),
        ),
        migrations.CreateModel(
            name="AppFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="vector_app.internalapp",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_favorites",
                        to="vector_app.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppDataTableSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema_json",
                    models.JSONField(help_text="Table schema frozen at this version"),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Table name at this version", max_length=255
                    ),
                ),
                (
                    "table_slug",
                    models.SlugField(
                        help_text="Table slug at this version", max_length=255
                    ),
                ),
                (
                    "table_description",
                    models.TextField(
                        blank=True, help_text="Table description at this version"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "CREATE"),
                            ("update", "UPDATE"),
                            ("delete", "DELETE"),
                        ],
                        help_text="Operation that created this snapshot",
                        max_length=20,
                    ),
                ),
                (
                    "previous_schema_json",
                    models.JSONField(
                        blank=True,
                        help_text="Previous schema (for update operations)",
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        help_text="The app version this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_snapshots",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="The table this snapshot is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="vector_app.appdatatable",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appdatatable",
            name="internal_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_tables",
                to="vector_app.internalapp",
            ),
        ),
        migrations.CreateModel(
            name="AppDataRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Row data matching table schema"
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(
                        help_text="Sequential index within table"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="vector_app.appdatatable",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index"],
            },
        ),
        migrations.CreateModel(
            name="VersionStateSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tables_json",
                    models.JSONField(
                        default=list,
                        help_text="Array of {id, slug, name, description, schema, row_count} for all tables",
                    ),
                ),
                (
                    "total_tables",
                    models.IntegerField(
                        default=0, help_text="Number of data tables at this version"
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(
                        default=0,
                        help_text="Total row count across all tables at this version",
                    ),
                ),
                (
                    "file_count",
                    models.IntegerField(
                        default=0, help_text="Number of code files at this version"
                    ),
                ),
                (
                    "app_version",
                    models.OneToOneField(
                        help_text="The version this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_snapshot",
                        to="vector_app.appversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["app_version"], name="vector_app__app_ver_47bb03_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VersionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=500)),
                ("content", models.TextField()),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Deterministic hash of the file content for integrity checks",
                        max_length=64,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="vector_app.appversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["app_version", "path"],
                        name="vector_app__app_ver_690af0_idx",
                    )
                ],
                "unique_together": {("app_version", "path")},
            },
        ),
        migrations.CreateModel(
            name="VersionAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "CREATE"),
                            ("rollback", "ROLLBACK"),
                            ("publish", "PUBLISH"),
                            ("schema_revert", "SCHEMA_REVERT"),
                            ("preview", "PREVIEW"),
                        ],
                        help_text="The type of operation performed",
                        max_length=20,
                    ),
                ),
                (
                    "details_json",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed operation context and parameters",
                    ),
                ),
                (
                    "schema_changes_json",
                    models.JSONField(
                        blank=True,
                        help_text="Summary of schema changes for rollback operations",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user performing the operation",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string of the client",
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the operation completed successfully",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if operation failed",
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        help_text="The version affected by this operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        help_text="The app this audit log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_audit_logs",
                        to="vector_app.internalapp",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="For rollback operations, the version being rolled back from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_audit_logs",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["internal_app", "-created_at"],
                        name="vector_app__interna_25a2ba_idx",
                    ),
                    models.Index(
                        fields=["app_version", "-created_at"],
                        name="vector_app__app_ver_492634_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="vector_app__user_id_0d8872_idx",
                    ),
                    models.Index(
                        fields=["operation", "-created_at"],
                        name="vector_app__operati_6ceed4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "ADMIN"),
                            ("editor", "EDITOR"),
                            ("viewer", "VIEWER"),
                        ],
                        default=vector_app.models.UserOrganizationRole["EDITOR"],
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_organizations",
                        to="vector_app.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "organization")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address this invitation is for",
                        max_length=254,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "ADMIN"),
                            ("editor", "EDITOR"),
                            ("viewer", "VIEWER"),
                        ],
                        default=vector_app.models.UserOrganizationRole["EDITOR"],
                        help_text="Role the user will have when they accept",
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA256 hash of the invitation token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this invitation expires"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted",
                        null=True,
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this invitation has been accepted",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="vector_app.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "email"],
                        name="vector_app__organiz_99937b_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="vector_app__expires_4c6454_idx"
                    ),
                    models.Index(
                        fields=["token_hash"], name="vector_app__token_h_81faef_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationConnectorLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_connected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the organization has connected this connector",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the connector was connected",
                        null=True,
                    ),
                ),
                (
                    "connection_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the connection",
                    ),
                ),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who connected this integration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connected_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_links",
                        to="vector_app.connectorcache",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_links",
                        to="vector_app.mergeintegrationprovider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "connector")},
            },
        ),
        migrations.AddIndex(
            model_name="internalapp",
            index=models.Index(
                fields=["organization", "slug"], name="vector_app__organiz_3793b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="internalapp",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="connectortoolaction",
            index=models.Index(
                fields=["connector_cache", "action_type"],
                name="vector_app__connect_c32923_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="connectortoolaction",
            index=models.Index(
                fields=["action_type"], name="vector_app__action__dfb2ca_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connectortoolaction",
            unique_together={("connector_cache", "tool_id")},
        ),
        migrations.AddIndex(
            model_name="connectorexecutionlog",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="vector_app__interna_964403_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="connectorexecutionlog",
            index=models.Index(
                fields=["user", "-created_at"], name="vector_app__user_id_9cff60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connectorexecutionlog",
            index=models.Index(
                fields=["connector_slug", "-created_at"],
                name="vector_app__connect_10afaa_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connectorcache",
            unique_together={("provider", "connector_id")},
        ),
        migrations.AddIndex(
            model_name="codegenerationjob",
            index=models.Index(
                fields=["internal_app", "status"], name="vector_app__interna_7baef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codegenerationjob",
            index=models.Index(
                fields=["status", "-created_at"], name="vector_app__status_1f9b8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="vector_app__interna_439373_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="vector_app__session_f77165_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appversion",
            index=models.Index(
                fields=["internal_app", "-version_number"],
                name="vector_app__interna_e966ef_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appversion",
            unique_together={("internal_app", "version_number")},
        ),
        migrations.AddIndex(
            model_name="appfavorite",
            index=models.Index(
                fields=["user", "organization"], name="vector_app__user_id_dc17f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appfavorite",
            unique_together={("user", "organization", "app")},
        ),
        migrations.AddIndex(
            model_name="appdatatablesnapshot",
            index=models.Index(
                fields=["app_version", "table"], name="vector_app__app_ver_cf820b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appdatatablesnapshot",
            index=models.Index(
                fields=["table", "created_at"], name="vector_app__table_i_b1b10d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appdatatablesnapshot",
            unique_together={("app_version", "table")},
        ),
        migrations.AddIndex(
            model_name="appdatatable",
            index=models.Index(
                fields=["internal_app", "slug"], name="vector_app__interna_75393c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appdatatable",
            unique_together={("internal_app", "slug")},
        ),
        migrations.AddIndex(
            model_name="appdatarow",
            index=models.Index(
                fields=["table", "row_index"], name="vector_app__table_i_626713_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appdatarow",
            index=models.Index(
                fields=["table", "created_at"], name="vector_app__table_i_3b2ee2_idx"
            ),
        ),
    ]
