# Generated by Django 5.2.9 on 2026-01-11 00:30

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackendConnection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "adapter_type",
                    models.CharField(
                        choices=[
                            ("supabase", "Supabase"),
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                        ],
                        default="supabase",
                        max_length=50,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "config_encrypted",
                    models.TextField(help_text="Encrypted JSON configuration"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConnectorCache",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connector_id",
                    models.CharField(
                        help_text='Connector ID from Merge (e.g., "jira", "linear", "slack")',
                        max_length=255,
                    ),
                ),
                (
                    "connector_name",
                    models.CharField(
                        help_text='Display name (e.g., "Jira", "Linear", "Slack")',
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text='Category (e.g., "project_management", "communication")',
                        max_length=100,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="URL to connector logo image", null=True
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text='Source website URL (e.g., "https://linear.app")',
                        null=True,
                    ),
                ),
                (
                    "categories_json",
                    models.JSONField(
                        default=list,
                        help_text='List of category tags (e.g., ["Project Management", "Ticketing"])',
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the connector"
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        help_text="Deprecated: Use logo_url instead",
                        null=True,
                    ),
                ),
                (
                    "tools_json",
                    models.JSONField(
                        default=list,
                        help_text="List of available tools: [{id, name, description, parameters}]",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this connector is enabled for the organization",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this connector was synced from Merge",
                    ),
                ),
            ],
            options={
                "ordering": ["connector_name"],
            },
        ),
        migrations.CreateModel(
            name="MergeIntegrationProvider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "merge_tool_pack_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DEPRECATED: Tool Pack ID now comes from environment variables",
                        max_length=255,
                    ),
                ),
                (
                    "merge_access_key_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="DEPRECATED: Access key now comes from environment variables",
                    ),
                ),
                (
                    "merge_registered_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Organization registered user ID from Merge (set after first link)",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(default="Integrations", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo image",
                        null=True,
                        upload_to="org_logos/",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True,
                        help_text="Google user ID for OAuth",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "profile_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Profile image URL from OAuth provider",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "spec_json",
                    models.JSONField(help_text="AppSpec JSON for this version"),
                ),
                (
                    "scope_snapshot_json",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of resource registry scope for published versions",
                        null=True,
                    ),
                ),
                (
                    "intent_message",
                    models.TextField(
                        blank=True,
                        help_text="User intent that generated this version (AI edits)",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai_edit", "AI Edit"),
                            ("code_edit", "Code Edit"),
                            ("rollback", "Rollback"),
                            ("publish", "Publish"),
                            ("ai", "AI (legacy)"),
                            ("code", "Code (legacy)"),
                        ],
                        default="ai_edit",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this version is active and should be returned by API. Only set True when generation completes successfully.",
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="complete",
                        help_text="Status of agentic code generation",
                        max_length=20,
                    ),
                ),
                (
                    "generation_plan_json",
                    models.JSONField(
                        blank=True,
                        help_text="Current plan for agentic generation",
                        null=True,
                    ),
                ),
                (
                    "generation_current_step",
                    models.IntegerField(
                        default=0, help_text="Current step index in generation plan"
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="TypeScript compilation validation status",
                        max_length=20,
                    ),
                ),
                (
                    "validation_errors_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of validation errors if failed",
                        null=True,
                    ),
                ),
                (
                    "fix_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of auto-fix attempts made"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent version used as the base for this version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="vector_app.appversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Chat", max_length=255)),
                (
                    "model_id",
                    models.CharField(
                        default="anthropic/claude-sonnet-4",
                        help_text="AI model used for this session",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("streaming", "Streaming"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        default="complete",
                        max_length=20,
                    ),
                ),
                ("model_id", models.CharField(blank=True, max_length=100, null=True)),
                ("token_count_input", models.IntegerField(blank=True, null=True)),
                ("token_count_output", models.IntegerField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                (
                    "generated_spec_json",
                    models.JSONField(
                        blank=True,
                        help_text="Generated AppSpec JSON if this was a spec generation",
                        null=True,
                    ),
                ),
                (
                    "generated_files",
                    models.JSONField(
                        blank=True,
                        help_text="Generated code files {path: content}",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "version_created",
                    models.ForeignKey(
                        blank=True,
                        help_text="Version created from this message",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_messages",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="vector_app.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InternalApp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier for the app (auto-generated from name if not set)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("allow_actions_in_preview", models.BooleanField(default=False)),
                (
                    "backend_connection",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional backend connection for data access",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_apps",
                        to="vector_app.backendconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The currently active published version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_for_app",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_apps",
                        to="vector_app.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConnectorExecutionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connector_slug",
                    models.CharField(
                        help_text='Connector ID slug (e.g., "jira")', max_length=255
                    ),
                ),
                ("tool_id", models.CharField(max_length=255)),
                (
                    "params_json",
                    models.JSONField(default=dict, help_text="Input parameters"),
                ),
                (
                    "result_json",
                    models.JSONField(
                        blank=True, help_text="Execution result", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="vector_app.connectorcache",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connector_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_logs",
                        to="vector_app.internalapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeGenerationJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_message", models.TextField(blank=True)),
                (
                    "model_id",
                    models.CharField(
                        default="anthropic/claude-sonnet-4", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("streaming", "Streaming"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("progress_message", models.CharField(blank=True, max_length=255)),
                ("accumulated_content", models.TextField(blank=True)),
                ("chunk_count", models.IntegerField(default=0)),
                ("events_json", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                (
                    "chat_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_job",
                        to="vector_app.chatmessage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="vector_app.chatsession",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_job",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to="vector_app.internalapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="internal_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="vector_app.internalapp",
            ),
        ),
        migrations.AddField(
            model_name="appversion",
            name="internal_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="vector_app.internalapp",
            ),
        ),
        migrations.CreateModel(
            name="AppDataTable",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "schema_json",
                    models.JSONField(
                        default=dict,
                        help_text="Table schema: columns, types, constraints",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_tables",
                        to="vector_app.internalapp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppDataQuery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "query_spec",
                    models.JSONField(
                        help_text="Query specification: filters, sort, pagination"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_queries",
                        to="vector_app.appdatatable",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_queries",
                        to="vector_app.internalapp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionExecutionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_id", models.CharField(max_length=255)),
                (
                    "resource_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "args_json",
                    models.JSONField(default=dict, help_text="Input arguments payload"),
                ),
                (
                    "result_json",
                    models.JSONField(
                        blank=True, help_text="Adapter execution result", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "backend_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to="vector_app.backendconnection",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="vector_app.internalapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MagicLinkToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address this magic link is for",
                        max_length=254,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA256 hash of the magic link token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this magic link expires"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Whether this token has been used"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name for new user registration",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name for new user registration",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address that requested this magic link",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent that requested this magic link",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="vector_app__email_1626bc_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="vector_app__expires_24a522_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="connectorcache",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connectors",
                to="vector_app.mergeintegrationprovider",
            ),
        ),
        migrations.AddField(
            model_name="mergeintegrationprovider",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integration_providers",
                to="vector_app.organization",
            ),
        ),
        migrations.AddField(
            model_name="backendconnection",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backend_connections",
                to="vector_app.organization",
            ),
        ),
        migrations.CreateModel(
            name="AppFavorite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="vector_app.internalapp",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_favorites",
                        to="vector_app.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_id", models.CharField(max_length=100)),
                ("request_type", models.CharField(max_length=50)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("cost_input_cents", models.IntegerField(default=0)),
                ("cost_output_cents", models.IntegerField(default=0)),
                ("total_cost_cents", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="vector_app.chatmessage",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to="vector_app.internalapp",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to="vector_app.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_model",
                    models.CharField(
                        default="anthropic/claude-sonnet-4", max_length=100
                    ),
                ),
                (
                    "fallback_model",
                    models.CharField(
                        default="openai/gpt-4o-mini",
                        help_text="Model to use if primary fails",
                        max_length=100,
                    ),
                ),
                ("temperature", models.FloatField(default=0.3)),
                ("max_tokens", models.IntegerField(default=8192)),
                (
                    "system_prompt_override",
                    models.TextField(
                        blank=True,
                        help_text="Custom system prompt to prepend",
                        null=True,
                    ),
                ),
                (
                    "coding_guidelines",
                    models.TextField(
                        blank=True,
                        help_text="Custom coding guidelines for generation",
                        null=True,
                    ),
                ),
                ("enable_streaming", models.BooleanField(default=True)),
                (
                    "enable_auto_apply",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-apply generated code without confirmation",
                    ),
                ),
                (
                    "enable_thinking_display",
                    models.BooleanField(
                        default=True, help_text="Show AI thinking process"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_configs",
                        to="vector_app.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationConnectorLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_connected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the organization has connected this connector",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the connector was connected",
                        null=True,
                    ),
                ),
                (
                    "connection_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the connection",
                    ),
                ),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who connected this integration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connected_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_links",
                        to="vector_app.connectorcache",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_links",
                        to="vector_app.mergeintegrationprovider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationInvite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Email address this invitation is for",
                        max_length=254,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="editor",
                        help_text="Role the user will have when they accept",
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA256 hash of the invitation token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this invitation expires"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted",
                        null=True,
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this invitation has been accepted",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="User who sent the invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="vector_app.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUserBackendAuth",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_jwt_encrypted",
                    models.TextField(help_text="Encrypted user JWT"),
                ),
                (
                    "backend_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_auths",
                        to="vector_app.backendconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backend_auths",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceRegistryEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource_id", models.CharField(max_length=255)),
                ("resource_name", models.CharField(max_length=255)),
                (
                    "schema_json",
                    models.JSONField(help_text="JSON schema for this resource"),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "exposed_fields_json",
                    models.JSONField(
                        default=list, help_text="List of field names that are exposed"
                    ),
                ),
                (
                    "ui_constraints_json",
                    models.JSONField(
                        default=dict, help_text="UI constraints (read_only, etc.)"
                    ),
                ),
                (
                    "allowed_actions_json",
                    models.JSONField(
                        default=list, help_text="List of allowed ActionDef JSON objects"
                    ),
                ),
                (
                    "backend_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_registry_entries",
                        to="vector_app.backendconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_registry_entries",
                        to="vector_app.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserOrganization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("editor", "Editor"),
                            ("viewer", "Viewer"),
                        ],
                        default="editor",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_organizations",
                        to="vector_app.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersionAuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("rollback", "Rollback"),
                            ("publish", "Publish"),
                            ("schema_revert", "Schema Revert"),
                            ("preview", "Preview"),
                        ],
                        help_text="The type of operation performed",
                        max_length=20,
                    ),
                ),
                (
                    "details_json",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed operation context and parameters",
                    ),
                ),
                (
                    "schema_changes_json",
                    models.JSONField(
                        blank=True,
                        help_text="Summary of schema changes for rollback operations",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the user performing the operation",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent string of the client",
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the operation completed successfully",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if operation failed",
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        help_text="The version affected by this operation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        help_text="The app this audit log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_audit_logs",
                        to="vector_app.internalapp",
                    ),
                ),
                (
                    "source_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="For rollback operations, the version being rolled back from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_audit_logs",
                        to="vector_app.appversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed this operation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="version_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VersionFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("content", models.TextField()),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Deterministic hash of the file content for integrity checks",
                        max_length=64,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="vector_app.appversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersionStateSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tables_json",
                    models.JSONField(
                        default=list,
                        help_text="Array of {id, slug, name, description, schema, row_count} for all tables",
                    ),
                ),
                (
                    "resources_json",
                    models.JSONField(
                        default=list,
                        help_text="Array of resource registry entries exposed to this app",
                    ),
                ),
                (
                    "total_tables",
                    models.IntegerField(
                        default=0, help_text="Number of data tables at this version"
                    ),
                ),
                (
                    "total_rows",
                    models.IntegerField(
                        default=0,
                        help_text="Total row count across all tables at this version",
                    ),
                ),
                (
                    "file_count",
                    models.IntegerField(
                        default=0, help_text="Number of code files at this version"
                    ),
                ),
                (
                    "app_version",
                    models.OneToOneField(
                        help_text="The version this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_snapshot",
                        to="vector_app.appversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppDataRow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Row data matching table schema"
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(
                        help_text="Sequential index within table"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="vector_app.appdatatable",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index"],
                "indexes": [
                    models.Index(
                        fields=["table", "row_index"],
                        name="vector_app__table_i_626713_idx",
                    ),
                    models.Index(
                        fields=["table", "created_at"],
                        name="vector_app__table_i_3b2ee2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AppDataTableSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schema_json",
                    models.JSONField(help_text="Table schema frozen at this version"),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Table name at this version", max_length=255
                    ),
                ),
                (
                    "table_slug",
                    models.SlugField(
                        help_text="Table slug at this version", max_length=255
                    ),
                ),
                (
                    "table_description",
                    models.TextField(
                        blank=True, help_text="Table description at this version"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        help_text="Operation that created this snapshot",
                        max_length=20,
                    ),
                ),
                (
                    "previous_schema_json",
                    models.JSONField(
                        blank=True,
                        help_text="Previous schema (for update operations)",
                        null=True,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="The table this snapshot is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="vector_app.appdatatable",
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        help_text="The app version this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_snapshots",
                        to="vector_app.appversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["app_version", "table"],
                        name="vector_app__app_ver_cf820b_idx",
                    ),
                    models.Index(
                        fields=["table", "created_at"],
                        name="vector_app__table_i_b1b10d_idx",
                    ),
                ],
                "unique_together": {("app_version", "table")},
            },
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="vector_app__session_f77165_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connectorexecutionlog",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="vector_app__interna_964403_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="connectorexecutionlog",
            index=models.Index(
                fields=["user", "-created_at"], name="vector_app__user_id_9cff60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connectorexecutionlog",
            index=models.Index(
                fields=["connector_slug", "-created_at"],
                name="vector_app__connect_10afaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="codegenerationjob",
            index=models.Index(
                fields=["internal_app", "status"], name="vector_app__interna_7baef3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codegenerationjob",
            index=models.Index(
                fields=["status", "-created_at"], name="vector_app__status_1f9b8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="vector_app__interna_439373_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appversion",
            index=models.Index(
                fields=["internal_app", "-version_number"],
                name="vector_app__interna_e966ef_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appversion",
            unique_together={("internal_app", "version_number")},
        ),
        migrations.AddIndex(
            model_name="appdatatable",
            index=models.Index(
                fields=["internal_app", "slug"], name="vector_app__interna_75393c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appdatatable",
            unique_together={("internal_app", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="appdataquery",
            unique_together={("internal_app", "name")},
        ),
        migrations.AddIndex(
            model_name="actionexecutionlog",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="vector_app__interna_c6a96f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actionexecutionlog",
            index=models.Index(
                fields=["app_version", "-created_at"],
                name="vector_app__app_ver_5d2d07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="actionexecutionlog",
            index=models.Index(
                fields=["backend_connection", "-created_at"],
                name="vector_app__backend_03477c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connectorcache",
            unique_together={("provider", "connector_id")},
        ),
        migrations.AlterUniqueTogether(
            name="mergeintegrationprovider",
            unique_together={("organization",)},
        ),
        migrations.AddIndex(
            model_name="internalapp",
            index=models.Index(
                fields=["organization", "slug"], name="vector_app__organiz_3793b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="internalapp",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="appfavorite",
            index=models.Index(
                fields=["user", "organization"], name="vector_app__user_id_dc17f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appfavorite",
            unique_together={("user", "organization", "app")},
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="vector_app__organiz_2093d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["user", "-created_at"], name="vector_app__user_id_9c348a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["model_id", "-created_at"],
                name="vector_app__model_i_07908a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentconfiguration",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="organizationconnectorlink",
            unique_together={("provider", "connector")},
        ),
        migrations.AddIndex(
            model_name="organizationinvite",
            index=models.Index(
                fields=["organization", "email"], name="vector_app__organiz_99937b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationinvite",
            index=models.Index(
                fields=["expires_at"], name="vector_app__expires_4c6454_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationinvite",
            index=models.Index(
                fields=["token_hash"], name="vector_app__token_h_81faef_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectuserbackendauth",
            unique_together={("user", "backend_connection")},
        ),
        migrations.AddIndex(
            model_name="resourceregistryentry",
            index=models.Index(
                fields=["backend_connection", "resource_id"],
                name="vector_app__backend_0a156e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resourceregistryentry",
            unique_together={("backend_connection", "resource_id")},
        ),
        migrations.AlterUniqueTogether(
            name="userorganization",
            unique_together={("user", "organization")},
        ),
        migrations.AddIndex(
            model_name="versionauditlog",
            index=models.Index(
                fields=["internal_app", "-created_at"],
                name="vector_app__interna_25a2ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="versionauditlog",
            index=models.Index(
                fields=["app_version", "-created_at"],
                name="vector_app__app_ver_492634_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="versionauditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="vector_app__user_id_0d8872_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="versionauditlog",
            index=models.Index(
                fields=["operation", "-created_at"],
                name="vector_app__operati_6ceed4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="versionfile",
            index=models.Index(
                fields=["app_version", "path"], name="vector_app__app_ver_690af0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="versionfile",
            unique_together={("app_version", "path")},
        ),
        migrations.AddIndex(
            model_name="versionstatesnapshot",
            index=models.Index(
                fields=["app_version"], name="vector_app__app_ver_47bb03_idx"
            ),
        ),
    ]
