# Generated by Django 4.2.27 on 2026-01-15 03:46

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vector_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestioningSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "IN_PROGRESS"),
                            ("complete", "COMPLETE"),
                            ("skipped", "SKIPPED"),
                        ],
                        default=vector_app.models.QuestioningStatus["IN_PROGRESS"],
                        max_length=20,
                    ),
                ),
                (
                    "synthesized_requirements",
                    models.JSONField(
                        default=dict,
                        help_text="Final requirements document after questioning completes",
                    ),
                ),
                (
                    "question_count",
                    models.IntegerField(
                        default=0, help_text="Number of questions asked"
                    ),
                ),
                (
                    "initial_request",
                    models.TextField(
                        help_text="User's original request that triggered questioning"
                    ),
                ),
                (
                    "chat_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questioning_session",
                        to="vector_app.chatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
