# Generated by Django 5.2.9 on 2026-01-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo_storage_key",
            field=models.CharField(
                blank=True,
                help_text="Storage key for logo image (supports cloud and local storage)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Organization logo image (legacy - use logo_storage_key for new uploads)",
                null=True,
                upload_to="org_logos/",
            ),
        ),
    ]
