# Generated by Django 5.2.9 on 2026-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0002_add_logo_storage_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image_storage_key",
            field=models.CharField(
                blank=True,
                help_text="Storage key for uploaded profile image (supports cloud and local storage)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image_url",
            field=models.URLField(
                blank=True,
                help_text="Profile image URL from OAuth provider (legacy)",
                max_length=500,
                null=True,
            ),
        ),
    ]
