# Generated by Django 4.2.27 on 2026-01-16 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vector_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0002_questioningsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestioningJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "QUEUED"),
                            ("processing", "PROCESSING"),
                            ("waiting_for_answer", "WAITING_FOR_ANSWER"),
                            ("complete", "COMPLETE"),
                            ("skipped", "SKIPPED"),
                            ("failed", "FAILED"),
                        ],
                        default=vector_app.models.QuestioningJobStatus["QUEUED"],
                        max_length=20,
                    ),
                ),
                ("events_json", models.JSONField(blank=True, default=list)),
                ("current_question", models.TextField(blank=True)),
                ("user_answer", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questioning_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "questioning_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="vector_app.questioningsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="vector_app__status_67ddfc_idx"
                    ),
                    models.Index(
                        fields=["questioning_session", "status"],
                        name="vector_app__questio_7f4974_idx",
                    ),
                ],
            },
        ),
    ]
