# Generated by Django 4.2.27 on 2026-01-16

from django.db import migrations, models


def set_source_for_existing_messages(apps, schema_editor):
    """
    Set source='questioning' for all messages in sessions that have a QuestioningSession.
    
    This ensures existing questioning messages appear in the Requirements tab after
    we add source-based filtering.
    """
    ChatMessage = apps.get_model("vector_app", "ChatMessage")
    QuestioningSession = apps.get_model("vector_app", "QuestioningSession")
    
    # Get all chat session IDs that have an associated QuestioningSession
    questioning_session_ids = QuestioningSession.objects.values_list(
        "chat_session_id", flat=True
    )
    
    # Update all messages in those sessions to have source='questioning'
    ChatMessage.objects.filter(
        session_id__in=questioning_session_ids,
        source__isnull=True,
    ).update(source="questioning")


def reverse_source_migration(apps, schema_editor):
    """Reverse: set source back to null for questioning messages."""
    ChatMessage = apps.get_model("vector_app", "ChatMessage")
    ChatMessage.objects.filter(source="questioning").update(source=None)


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0003_questioningjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("questioning", "QUESTIONING"), ("build", "BUILD")],
                help_text="Source context: 'questioning' for Requirements tab, 'build' for Build tab",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "source"], name="vector_app__session_source_idx"
            ),
        ),
        # Run data migration to set source for existing questioning messages
        migrations.RunPython(set_source_for_existing_messages, reverse_source_migration),
    ]

