# Generated by Django 4.2.27 on 2026-01-12 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0002_connectortoolaction"),
        ("vector_app", "0003_add_profile_image_storage_key"),
    ]

    operations = []
