# Generated by Django 4.2.27 on 2026-01-12 23:37

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vector_app.action_classification.types


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0003_add_profile_image_storage_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectorToolAction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool_id",
                    models.CharField(
                        help_text='Tool identifier (e.g., "create_issue")',
                        max_length=255,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Display name for the tool", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the tool"
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict, help_text="Full JSON Schema for tool parameters"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("QUERY", "QUERY"),
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                            ("SEND", "SEND"),
                            ("OTHER", "OTHER"),
                        ],
                        default=vector_app.action_classification.types.ActionType[
                            "OTHER"
                        ],
                        help_text="Categorized action type (query, create, update, delete, send, other)",
                        max_length=20,
                    ),
                ),
                (
                    "connector_cache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorized_tools",
                        to="vector_app.connectorcache",
                    ),
                ),
            ],
            options={
                "ordering": ["action_type", "tool_name"],
                "indexes": [
                    models.Index(
                        fields=["connector_cache", "action_type"],
                        name="vector_app__connect_c32923_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="vector_app__action__dfb2ca_idx"
                    ),
                ],
                "unique_together": {("connector_cache", "tool_id")},
            },
        ),
    ]
