# Generated by Django 4.2.27 on 2026-01-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0004_connectortoolaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appversion",
            name="scope_snapshot_json",
        ),
        migrations.RemoveField(
            model_name="codegenerationjob",
            name="accumulated_content",
        ),
        migrations.RemoveField(
            model_name="codegenerationjob",
            name="max_retries",
        ),
        migrations.RemoveField(
            model_name="codegenerationjob",
            name="progress_message",
        ),
        migrations.RemoveField(
            model_name="codegenerationjob",
            name="progress_percentage",
        ),
        migrations.RemoveField(
            model_name="codegenerationjob",
            name="retry_count",
        ),
        migrations.RemoveField(
            model_name="internalapp",
            name="backend_connection",
        ),
        migrations.RemoveField(
            model_name="versionstatesnapshot",
            name="resources_json",
        ),
        migrations.DeleteModel(
            name="ActionExecutionLog",
        ),
        migrations.DeleteModel(
            name="AgentConfiguration",
        ),
        migrations.DeleteModel(
            name="AIUsageLog",
        ),
        migrations.DeleteModel(
            name="AppDataQuery",
        ),
        migrations.DeleteModel(
            name="BackendConnection",
        ),
        migrations.DeleteModel(
            name="ProjectUserBackendAuth",
        ),
        migrations.DeleteModel(
            name="ResourceRegistryEntry",
        ),
    ]
