# Generated by Django 4.2.27 on 2026-01-15 02:34

from django.db import migrations, models
import vector_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("vector_app", "0005_alter_agentconfiguration_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectorcache",
            name="icon_url",
        ),
        migrations.AlterField(
            model_name="appdatatablesnapshot",
            name="operation",
            field=models.CharField(
                choices=[
                    ("create", "CREATE"),
                    ("update", "UPDATE"),
                    ("delete", "DELETE"),
                ],
                help_text="Operation that created this snapshot",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="generation_status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("generating", "GENERATING"),
                    ("complete", "COMPLETE"),
                    ("error", "ERROR"),
                ],
                default=vector_app.models.AppVersionGenerationStatus["COMPLETE"],
                help_text="Status of agentic code generation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="source",
            field=models.CharField(
                choices=[
                    ("ai_edit", "AI_EDIT"),
                    ("code_edit", "CODE_EDIT"),
                    ("rollback", "ROLLBACK"),
                    ("publish", "PUBLISH"),
                    ("ai", "AI"),
                    ("code", "CODE"),
                ],
                default=vector_app.models.AppVersionSource["AI_EDIT"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appversion",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("passed", "PASSED"),
                    ("failed", "FAILED"),
                    ("skipped", "SKIPPED"),
                ],
                default=vector_app.models.AppVersionValidationStatus["PENDING"],
                help_text="TypeScript compilation validation status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "USER"),
                    ("assistant", "ASSISTANT"),
                    ("system", "SYSTEM"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("streaming", "STREAMING"),
                    ("complete", "COMPLETE"),
                    ("error", "ERROR"),
                ],
                default=vector_app.models.ChatMessageStatus["COMPLETE"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="codegenerationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "QUEUED"),
                    ("processing", "PROCESSING"),
                    ("streaming", "STREAMING"),
                    ("complete", "COMPLETE"),
                    ("failed", "FAILED"),
                    ("cancelled", "CANCELLED"),
                ],
                default=vector_app.models.CodeGenerationJobStatus["QUEUED"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="connectorexecutionlog",
            name="status",
            field=models.CharField(
                choices=[("success", "SUCCESS"), ("error", "ERROR")],
                default=vector_app.models.ConnectorExecutionStatus["SUCCESS"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="internalapp",
            name="status",
            field=models.CharField(
                choices=[("draft", "DRAFT"), ("published", "PUBLISHED")],
                default=vector_app.models.InternalAppStatus["DRAFT"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvite",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "ADMIN"),
                    ("editor", "EDITOR"),
                    ("viewer", "VIEWER"),
                ],
                default=vector_app.models.UserOrganizationRole["EDITOR"],
                help_text="Role the user will have when they accept",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userorganization",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "ADMIN"),
                    ("editor", "EDITOR"),
                    ("viewer", "VIEWER"),
                ],
                default=vector_app.models.UserOrganizationRole["EDITOR"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="versionauditlog",
            name="operation",
            field=models.CharField(
                choices=[
                    ("create", "CREATE"),
                    ("rollback", "ROLLBACK"),
                    ("publish", "PUBLISH"),
                    ("schema_revert", "SCHEMA_REVERT"),
                    ("preview", "PREVIEW"),
                ],
                help_text="The type of operation performed",
                max_length=20,
            ),
        ),
    ]
