# Generated by Django 6.0.1 on 2026-01-15 22:55

import apps.action_classification.types
import django.db.models.deletion
import integrations.types
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("apps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeIntegrationProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merge_tool_pack_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DEPRECATED: Tool Pack ID now comes from environment variables",
                        max_length=255,
                    ),
                ),
                (
                    "merge_access_key_encrypted",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="DEPRECATED: Access key now comes from environment variables",
                    ),
                ),
                (
                    "merge_registered_user_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Organization registered user ID from Merge (set after first link)",
                        max_length=255,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(default="Integrations", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_providers",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization",)},
            },
        ),
        migrations.CreateModel(
            name="ConnectorCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connector_id",
                    models.CharField(
                        help_text='Connector ID from Merge (e.g., "jira", "linear", "slack")',
                        max_length=255,
                    ),
                ),
                (
                    "connector_name",
                    models.CharField(
                        help_text='Display name (e.g., "Jira", "Linear", "Slack")',
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text='Category (e.g., "project_management", "communication")',
                        max_length=100,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="URL to connector logo image", null=True
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text='Source website URL (e.g., "https://linear.app")',
                        null=True,
                    ),
                ),
                (
                    "categories_json",
                    models.JSONField(
                        default=list,
                        help_text='List of category tags (e.g., ["Project Management", "Ticketing"])',
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the connector"
                    ),
                ),
                (
                    "tools_json",
                    models.JSONField(
                        default=list,
                        help_text="List of available tools: [{id, name, description, parameters}]",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this connector is enabled for the organization",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this connector was synced from Merge",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connectors",
                        to="integrations.mergeintegrationprovider",
                    ),
                ),
            ],
            options={
                "ordering": ["connector_name"],
                "unique_together": {("provider", "connector_id")},
            },
        ),
        migrations.CreateModel(
            name="ConnectorExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connector_slug",
                    models.CharField(
                        help_text='Connector ID slug (e.g., "jira")', max_length=255
                    ),
                ),
                ("tool_id", models.CharField(max_length=255)),
                (
                    "params_json",
                    models.JSONField(default=dict, help_text="Input parameters"),
                ),
                (
                    "result_json",
                    models.JSONField(
                        blank=True, help_text="Execution result", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "SUCCESS"), ("error", "ERROR")],
                        default=integrations.types.ConnectorExecutionStatus["SUCCESS"],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution duration in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_logs",
                        to="integrations.connectorcache",
                    ),
                ),
                (
                    "internal_app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_logs",
                        to="apps.internalapp",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connector_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["internal_app", "-created_at"],
                        name="integration_interna_7bc08c_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="integration_user_id_0028ae_idx",
                    ),
                    models.Index(
                        fields=["connector_slug", "-created_at"],
                        name="integration_connect_dfb01e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConnectorToolAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool_id",
                    models.CharField(
                        help_text='Tool identifier (e.g., "create_issue")',
                        max_length=255,
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        help_text="Display name for the tool", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the tool"
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict, help_text="Full JSON Schema for tool parameters"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("QUERY", "QUERY"),
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                            ("SEND", "SEND"),
                            ("OTHER", "OTHER"),
                        ],
                        default=apps.action_classification.types.ActionType["OTHER"],
                        help_text="Categorized action type (query, create, update, delete, send, other)",
                        max_length=20,
                    ),
                ),
                (
                    "connector_cache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorized_tools",
                        to="integrations.connectorcache",
                    ),
                ),
            ],
            options={
                "ordering": ["action_type", "tool_name"],
                "indexes": [
                    models.Index(
                        fields=["connector_cache", "action_type"],
                        name="integration_connect_0172a4_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="integration_action__fe2293_idx"
                    ),
                ],
                "unique_together": {("connector_cache", "tool_id")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationConnectorLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_connected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the organization has connected this connector",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the connector was connected",
                        null=True,
                    ),
                ),
                (
                    "connection_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the connection",
                    ),
                ),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who connected this integration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connected_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_links",
                        to="integrations.connectorcache",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connector_links",
                        to="integrations.mergeintegrationprovider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "connector")},
            },
        ),
    ]
