"""
Version serializers
"""
from rest_framework import serializers
from ..models import AppVersion, VersionFile


class VersionFileSerializer(serializers.ModelSerializer):
    """Serializer for VersionFile model."""
    
    class Meta:
        model = VersionFile
        fields = [
            'id',
            'app_version',
            'path',
            'content',
            'content_hash',
            'created_at',
        ]
        read_only_fields = ['id', 'content_hash', 'created_at']


class AppVersionSerializer(serializers.ModelSerializer):
    """Serializer for AppVersion model."""
    source_display = serializers.CharField(source='get_source_display', read_only=True)
    created_by_email = serializers.EmailField(source='created_by.email', read_only=True)
    files = VersionFileSerializer(many=True, read_only=True)
    
    class Meta:
        model = AppVersion
        fields = [
            'id',
            'internal_app',
            'version_number',
            'source',
            'source_display',
            'spec_json',
            'scope_snapshot_json',
            'created_by',
            'created_by_email',
            'created_at',
            'files',
        ]
        read_only_fields = ['id', 'version_number', 'created_by', 'created_at']


class AppVersionCreateSerializer(serializers.Serializer):
    """Serializer for creating app versions (used by ai-edit, code-edit)."""
    intent_message = serializers.CharField(required=False, allow_blank=True)
    spec_json = serializers.DictField(required=False)  # Not required for ai-edit (generated by AI)
    source = serializers.ChoiceField(choices=AppVersion.SOURCE_CHOICES, required=False)
    
    def validate_spec_json(self, value):
        """Validate spec_json structure."""
        if value and not isinstance(value, dict):
            raise serializers.ValidationError("spec_json must be a dictionary.")
        return value


class CodeEditSerializer(serializers.Serializer):
    """Serializer for code edits."""
    file_path = serializers.CharField(max_length=500)
    content = serializers.CharField()

