# Generated by Django 6.0.1 on 2026-01-15 22:55

import apps.types
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                (
                    "spec_json",
                    models.JSONField(help_text="AppSpec JSON for this version"),
                ),
                (
                    "intent_message",
                    models.TextField(
                        blank=True,
                        help_text="User intent that generated this version (AI edits)",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai_edit", "AI_EDIT"),
                            ("code_edit", "CODE_EDIT"),
                            ("rollback", "ROLLBACK"),
                            ("publish", "PUBLISH"),
                            ("ai", "AI"),
                            ("code", "CODE"),
                        ],
                        default=apps.types.AppVersionSource["AI_EDIT"],
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this version is active and should be returned by API. Only set True when generation completes successfully.",
                    ),
                ),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("generating", "GENERATING"),
                            ("complete", "COMPLETE"),
                            ("error", "ERROR"),
                        ],
                        default=apps.types.AppVersionGenerationStatus["COMPLETE"],
                        help_text="Status of agentic code generation",
                        max_length=20,
                    ),
                ),
                (
                    "generation_plan_json",
                    models.JSONField(
                        blank=True,
                        help_text="Current plan for agentic generation",
                        null=True,
                    ),
                ),
                (
                    "generation_current_step",
                    models.IntegerField(
                        default=0, help_text="Current step index in generation plan"
                    ),
                ),
                (
                    "generation_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if generation failed",
                        null=True,
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("passed", "PASSED"),
                            ("failed", "FAILED"),
                            ("skipped", "SKIPPED"),
                        ],
                        default=apps.types.AppVersionValidationStatus["PENDING"],
                        help_text="TypeScript compilation validation status",
                        max_length=20,
                    ),
                ),
                (
                    "validation_errors_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON list of validation errors if failed",
                        null=True,
                    ),
                ),
                (
                    "fix_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of auto-fix attempts made"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent version used as the base for this version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_versions",
                        to="apps.appversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="InternalApp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier for the app (auto-generated from name if not set)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "DRAFT"), ("published", "PUBLISHED")],
                        default=apps.types.InternalAppStatus["DRAFT"],
                        max_length=20,
                    ),
                ),
                ("allow_actions_in_preview", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_apps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_apps",
                        to="accounts.organization",
                    ),
                ),
                (
                    "published_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The currently active published version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_for_app",
                        to="apps.appversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appversion",
            name="internal_app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="apps.internalapp",
            ),
        ),
        migrations.CreateModel(
            name="AppFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_favorites",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="apps.internalapp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersionFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=500)),
                ("content", models.TextField()),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Deterministic hash of the file content for integrity checks",
                        max_length=64,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="apps.appversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="internalapp",
            index=models.Index(
                fields=["organization", "slug"], name="apps_intern_organiz_ca2ab0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="internalapp",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="appversion",
            index=models.Index(
                fields=["internal_app", "-version_number"],
                name="apps_appver_interna_39d37a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appversion",
            unique_together={("internal_app", "version_number")},
        ),
        migrations.AddIndex(
            model_name="appfavorite",
            index=models.Index(
                fields=["user", "organization"], name="apps_appfav_user_id_25dadf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appfavorite",
            unique_together={("user", "organization", "app")},
        ),
        migrations.AddIndex(
            model_name="versionfile",
            index=models.Index(
                fields=["app_version", "path"], name="apps_versio_app_ver_1a582a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="versionfile",
            unique_together={("app_version", "path")},
        ),
    ]
