# Generated by Django 6.0.1 on 2026-01-15 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppDataTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "schema_json",
                    models.JSONField(
                        default=dict,
                        help_text="Table schema: columns, types, constraints",
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "internal_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_tables",
                        to="apps.internalapp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppDataRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Row data matching table schema"
                    ),
                ),
                (
                    "row_index",
                    models.PositiveIntegerField(
                        help_text="Sequential index within table"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="data_store.appdatatable",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index"],
            },
        ),
        migrations.CreateModel(
            name="AppDataTableSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schema_json",
                    models.JSONField(help_text="Table schema frozen at this version"),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Table name at this version", max_length=255
                    ),
                ),
                (
                    "table_slug",
                    models.SlugField(
                        help_text="Table slug at this version", max_length=255
                    ),
                ),
                (
                    "table_description",
                    models.TextField(
                        blank=True, help_text="Table description at this version"
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("create", "CREATE"),
                            ("update", "UPDATE"),
                            ("delete", "DELETE"),
                        ],
                        help_text="Operation that created this snapshot",
                        max_length=20,
                    ),
                ),
                (
                    "previous_schema_json",
                    models.JSONField(
                        blank=True,
                        help_text="Previous schema (for update operations)",
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.ForeignKey(
                        help_text="The app version this snapshot belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_snapshots",
                        to="apps.appversion",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="The table this snapshot is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="data_store.appdatatable",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="appdatatable",
            index=models.Index(
                fields=["internal_app", "slug"], name="data_store__interna_8d03ce_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appdatatable",
            unique_together={("internal_app", "slug")},
        ),
        migrations.AddIndex(
            model_name="appdatarow",
            index=models.Index(
                fields=["table", "row_index"], name="data_store__table_i_8bbb29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appdatarow",
            index=models.Index(
                fields=["table", "created_at"], name="data_store__table_i_433e0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appdatatablesnapshot",
            index=models.Index(
                fields=["app_version", "table"], name="data_store__app_ver_9cbee9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appdatatablesnapshot",
            index=models.Index(
                fields=["table", "created_at"], name="data_store__table_i_74cdf2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appdatatablesnapshot",
            unique_together={("app_version", "table")},
        ),
    ]
